name: Build ISO

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ISO
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build ISO via Universal Blue Action
        uses: ublue-os/isogenerator@main
        with:
          image_name: distro-test
          image_repo: ghcr.io/x4eros
          image_tag: latest
          installer_version: 44 # Use 43 or a stable version that successfully builds your container image first
